// Code generated by protoc-gen-connect-swift. DO NOT EDIT.
//
// Source: research/gtfs_realtime/v1/gtfs_realtime.proto
//

import Connect
import Foundation
import SwiftProtobuf

public protocol Research_GtfsRealtime_V1_GtfsrealtimeServiceClientInterface: Sendable {

    @available(iOS 13, *)
    func `listVehiclePositions`(request: Research_GtfsRealtime_V1_ListVehiclePositionsRequest, headers: Connect.Headers) async -> ResponseMessage<Research_GtfsRealtime_V1_ListVehiclePositionsResponse>
}

/// Concrete implementation of `Research_GtfsRealtime_V1_GtfsrealtimeServiceClientInterface`.
public final class Research_GtfsRealtime_V1_GtfsrealtimeServiceClient: Research_GtfsRealtime_V1_GtfsrealtimeServiceClientInterface, Sendable {
    private let client: Connect.ProtocolClientInterface

    public init(client: Connect.ProtocolClientInterface) {
        self.client = client
    }

    @available(iOS 13, *)
    public func `listVehiclePositions`(request: Research_GtfsRealtime_V1_ListVehiclePositionsRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<Research_GtfsRealtime_V1_ListVehiclePositionsResponse> {
        return await self.client.unary(path: "/research.gtfs_realtime.v1.GTFSRealtimeService/ListVehiclePositions", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    public enum Metadata {
        public enum Methods {
            public static let listVehiclePositions = Connect.MethodSpec(name: "ListVehiclePositions", service: "research.gtfs_realtime.v1.GTFSRealtimeService", type: .unary)
        }
    }
}
